import os
file = open("pass.txt", "r+")
Pass = file.readline()
print(Pass)
os.system("git init")
os.system("git add .")
os.system("git commit -m \"first commit\"")
os.system("git branch -M master")
# os.system("git remote add origin git@github.com:sladememarian/password.git")
os.system("git push -u origin master")
